# Generated by Django 4.0.3 on 2022-04-09 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iris_users', '0002_alter_accountactivation_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irisuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
