# Generated by Django 4.0.4 on 2022-05-23 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_open_by', models.JSONField(default=dict, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('media', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DirectChannel',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iris_messages.channel')),
            ],
            bases=('iris_messages.channel',),
        ),
        migrations.CreateModel(
            name='GroupChannel',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iris_messages.channel')),
                ('name', models.TextField(max_length=32, null=True)),
            ],
            bases=('iris_messages.channel',),
        ),
    ]
