# Generated by Django 4.0.2 on 2022-03-23 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iris_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_messages.channel'),
        ),
        migrations.AddField(
            model_name='mediamessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_message_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediamessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_messages.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(related_name='channel_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchannel',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchannel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
