# Generated by Django 4.0.3 on 2022-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.BooleanField(default=False),
        ),
    ]
