# Generated by Django 4.0.2 on 2022-03-29 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iris_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='groupchannel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
