# Generated by Django 4.0.4 on 2022-04-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_messages', '0002_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
