# Generated by Django 4.0.4 on 2022-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_messages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
