# Generated by Django 4.0.2 on 2022-03-17 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iris_messages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(null=True)),
                ('media', models.FileField(upload_to=iris_messages.models.file_path)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_message_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupChannel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='channel_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectChannel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('users', models.ManyToManyField(max_length=2, related_name='user2user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
