# Generated by Django 4.0.2 on 2022-03-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_messages', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchannel',
            name='name',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='FriendShip',
        ),
    ]
