# Generated by Django 4.0.3 on 2022-04-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iris.profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iris_users', '0002_alter_accountactivation_activation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.FileField(blank=True, default=None, null=True, upload_to=iris.profiles.models.avatar_file_path)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
